import type { ViewTask } from '@zemen/react';

export const MOCK_TASKS: ViewTask[] = [
  {
    id: 'eth-1',
    title: 'Ethiopian New Year',
    dateType: 'ethiopian',
    primaryYear: 2017,
    primaryMonth: 1,
    primaryDay: 1,
    time: null,
    priority: 'high',
    status: 'pending',
    isAllDay: true,
  },
  {
    id: 'greg-1',
    title: 'Design review',
    dateType: 'gregorian',
    primaryYear: 2025,
    primaryMonth: 9,
    primaryDay: 11,
    time: '10:00',
    priority: 'high',
    status: 'pending',
  },
  {
    id: 'eth-2',
    title: 'Team standup',
    dateType: 'ethiopian',
    primaryYear: 2017,
    primaryMonth: 1,
    primaryDay: 3,
    time: '09:00',
    priority: 'medium',
    status: 'pending',
  },
  {
    id: 'eth-3',
    title: 'Project deadline',
    dateType: 'ethiopian',
    primaryYear: 2017,
    primaryMonth: 1,
    primaryDay: 5,
    time: '17:00',
    priority: 'urgent',
    status: 'pending',
  },
  {
    id: 'eth-4',
    title: 'Team lunch',
    dateType: 'ethiopian',
    primaryYear: 2017,
    primaryMonth: 1,
    primaryDay: 8,
    time: '12:30',
    priority: 'low',
    status: 'pending',
  },
  {
    id: 'all-day-1',
    title: 'Company retreat',
    dateType: 'ethiopian',
    primaryYear: 2017,
    primaryMonth: 1,
    primaryDay: 10,
    time: null,
    priority: 'medium',
    status: 'pending',
    isAllDay: true,
    endYear: 2017,
    endMonth: 1,
    endDay: 12,
  },
];
